import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Moment from 'react-moment'
import 'moment-timezone'
import moment from 'moment'
import Date from './Date'
// const dateToFormat = '1976-04-19T12:59-0500';
export default function Home() {
  return (
    <div>
      <Head>
        <title>Jeremy | Status</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-screen">
        <nav className="h-[4em] bg-[#2a2e35] flex items-center justify-between px-8">
          <div className="text-[#b2becd] font-bold text-2xl">Jeremy Status</div>
          <ul className="flex space-x-9 text-white font-bold text-xl">
            <li className="text-[#b2becd]">
              <Date />
            </li>
            {/* <li>Language</li> */}
          </ul>
        </nav>
        <div className="h-[84vh] bg-[#12181b] flex items-center justify-center">
          <div className="text-white text-9xl">Sleeping 💤</div>
        </div>
        <footer>
          <div className="h-[8vh] bg-[#2a2e35] flex items-center justify-center">
            <div className="text-white font-bold text-md">
              Made with ❤️ by Jeremy
            </div>
          </div>
        </footer>
      </div>
    </div>
  )
}
