import Head from 'next/head'
import { Navbar, Footer, Sleep } from './components'

export default function Home() {
	return (
		<div>
			<Head>
				<title>Jeremy | Status</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="h-screen overflow-x-hidden">
				<Navbar />
				<Sleep />
				<Footer />
			</div>
		</div>
	)
}
